# Generated by Django 5.0.7 on 2024-07-29 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('title_tr', models.CharField(blank=True, max_length=200, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_tr', models.CharField(blank=True, max_length=200, null=True)),
                ('address_en', models.CharField(blank=True, max_length=200, null=True)),
                ('address_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('address_ru', models.CharField(blank=True, max_length=200, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=200, null=True)),
                ('github', models.CharField(blank=True, max_length=200, null=True)),
                ('description1', models.TextField()),
                ('description1_tr', models.TextField(null=True)),
                ('description1_en', models.TextField(null=True)),
                ('description1_ar', models.TextField(null=True)),
                ('description1_ru', models.TextField(null=True)),
                ('description2', models.TextField()),
                ('description2_tr', models.TextField(null=True)),
                ('description2_en', models.TextField(null=True)),
                ('description2_ar', models.TextField(null=True)),
                ('description2_ru', models.TextField(null=True)),
                ('sub_description1', models.TextField()),
                ('sub_description1_tr', models.TextField(null=True)),
                ('sub_description1_en', models.TextField(null=True)),
                ('sub_description1_ar', models.TextField(null=True)),
                ('sub_description1_ru', models.TextField(null=True)),
                ('sub_description2', models.TextField()),
                ('sub_description2_tr', models.TextField(null=True)),
                ('sub_description2_en', models.TextField(null=True)),
                ('sub_description2_ar', models.TextField(null=True)),
                ('sub_description2_ru', models.TextField(null=True)),
                ('startedDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_tr', models.CharField(max_length=200, null=True)),
                ('name_en', models.CharField(max_length=200, null=True)),
                ('name_ar', models.CharField(max_length=200, null=True)),
                ('name_ru', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('description_tr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_ru', models.TextField(null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('startedDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField(auto_now_add=True)),
                ('about', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publish.about')),
            ],
        ),
    ]
