# Generated by Django 5.0.7 on 2024-08-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='name_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='name_tr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
