# Generated by Django 5.0.7 on 2024-08-14 16:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_home_description_ar_home_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='description_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
