# Generated by Django 5.0.7 on 2024-08-14 17:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_about_description3_alter_about_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='description3_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description3_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description3_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='description3_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
