# Generated by Django 5.0.7 on 2024-08-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0010_autism_subjectcontact_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectcontact',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
