# Generated by Django 5.1 on 2024-08-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0014_autism_description_ar_autism_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autism',
            name='startedDate',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
