# Generated by Django 5.1 on 2024-08-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0015_alter_autism_starteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='autism',
            name='startedDate_ar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='autism',
            name='startedDate_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='autism',
            name='startedDate_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='autism',
            name='startedDate_tr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
