# Generated by Django 5.1 on 2024-08-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0016_autism_starteddate_ar_autism_starteddate_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autism',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
