# Generated by Django 5.1 on 2024-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0019_rarediseases_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='otherSubject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
