# Generated by Django 5.1 on 2024-08-20 05:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0020_contact_othersubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
