# Generated by Django 5.1 on 2024-08-20 06:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0023_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
