# Generated by Django 5.1 on 2024-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0027_remove_books_image1_remove_books_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
    ]
